# worker/wrangler.toml
name = 'project-awid'
main = "worker/worker.js"
compatibility_date = "2024-01-01"

[vars]
GITHUB_REPO_OWNER = "Amychan-air"
GITHUB_REPO_NAME = "project-AWID"
GITHUB_BRANCH = "main"
