# worker/wrangler.toml
name = 'project-awid'
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
GITHUB_REPO_OWNER = "Amychan-air"
GITHUB_REPO_NAME = "project-AWID"
GITHUB_BRANCH = "main"
# GITHUB_TOKEN = "abcdefghijklmn"
# ADMIN_USERNAME = "admin"
# ADMIN_PASSWORD = "123456"  # 请修改为您想要的密码

# GitHub Token 是敏感信息，应在本地开发环境中通过命令行设置，或者在 Cloudflare 面板中设置
# 如果您想在本地测试，可以通过运行以下命令设置环境变量：
# wrangler secret put GITHUB_TOKEN
# 然后在提示中输入您的 GitHub Personal Access Token
